# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/FluidSimulation/FluidSimulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/FluidSimulation/FluidSimulation/build_site

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/FluidSimulation/FluidSimulation/build_site/CMakeFiles /home/runner/work/FluidSimulation/FluidSimulation/build_site/src//CMakeFiles/progress.marks
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/FluidSimulation/FluidSimulation/build_site/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/CMakeFiles/Fluid.dir/rule:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/CMakeFiles/Fluid.dir/rule
.PHONY : src/CMakeFiles/Fluid.dir/rule

# Convenience name for target.
Fluid: src/CMakeFiles/Fluid.dir/rule
.PHONY : Fluid

# fast build rule for target.
Fluid/fast:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/build
.PHONY : Fluid/fast

ControlPanel/control_panel.o: ControlPanel/control_panel.cpp.o
.PHONY : ControlPanel/control_panel.o

# target to build an object file
ControlPanel/control_panel.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/ControlPanel/control_panel.cpp.o
.PHONY : ControlPanel/control_panel.cpp.o

ControlPanel/control_panel.i: ControlPanel/control_panel.cpp.i
.PHONY : ControlPanel/control_panel.i

# target to preprocess a source file
ControlPanel/control_panel.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/ControlPanel/control_panel.cpp.i
.PHONY : ControlPanel/control_panel.cpp.i

ControlPanel/control_panel.s: ControlPanel/control_panel.cpp.s
.PHONY : ControlPanel/control_panel.s

# target to generate assembly for a file
ControlPanel/control_panel.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/ControlPanel/control_panel.cpp.s
.PHONY : ControlPanel/control_panel.cpp.s

ControlPanel/gui.o: ControlPanel/gui.cpp.o
.PHONY : ControlPanel/gui.o

# target to build an object file
ControlPanel/gui.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/ControlPanel/gui.cpp.o
.PHONY : ControlPanel/gui.cpp.o

ControlPanel/gui.i: ControlPanel/gui.cpp.i
.PHONY : ControlPanel/gui.i

# target to preprocess a source file
ControlPanel/gui.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/ControlPanel/gui.cpp.i
.PHONY : ControlPanel/gui.cpp.i

ControlPanel/gui.s: ControlPanel/gui.cpp.s
.PHONY : ControlPanel/gui.s

# target to generate assembly for a file
ControlPanel/gui.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/ControlPanel/gui.cpp.s
.PHONY : ControlPanel/gui.cpp.s

Fluid/fluid.o: Fluid/fluid.cpp.o
.PHONY : Fluid/fluid.o

# target to build an object file
Fluid/fluid.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/fluid.cpp.o
.PHONY : Fluid/fluid.cpp.o

Fluid/fluid.i: Fluid/fluid.cpp.i
.PHONY : Fluid/fluid.i

# target to preprocess a source file
Fluid/fluid.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/fluid.cpp.i
.PHONY : Fluid/fluid.cpp.i

Fluid/fluid.s: Fluid/fluid.cpp.s
.PHONY : Fluid/fluid.s

# target to generate assembly for a file
Fluid/fluid.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/fluid.cpp.s
.PHONY : Fluid/fluid.cpp.s

Fluid/logic.o: Fluid/logic.cpp.o
.PHONY : Fluid/logic.o

# target to build an object file
Fluid/logic.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/logic.cpp.o
.PHONY : Fluid/logic.cpp.o

Fluid/logic.i: Fluid/logic.cpp.i
.PHONY : Fluid/logic.i

# target to preprocess a source file
Fluid/logic.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/logic.cpp.i
.PHONY : Fluid/logic.cpp.i

Fluid/logic.s: Fluid/logic.cpp.s
.PHONY : Fluid/logic.s

# target to generate assembly for a file
Fluid/logic.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/logic.cpp.s
.PHONY : Fluid/logic.cpp.s

Fluid/util.o: Fluid/util.cpp.o
.PHONY : Fluid/util.o

# target to build an object file
Fluid/util.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/util.cpp.o
.PHONY : Fluid/util.cpp.o

Fluid/util.i: Fluid/util.cpp.i
.PHONY : Fluid/util.i

# target to preprocess a source file
Fluid/util.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/util.cpp.i
.PHONY : Fluid/util.cpp.i

Fluid/util.s: Fluid/util.cpp.s
.PHONY : Fluid/util.s

# target to generate assembly for a file
Fluid/util.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Fluid/util.cpp.s
.PHONY : Fluid/util.cpp.s

Render/draw.o: Render/draw.cpp.o
.PHONY : Render/draw.o

# target to build an object file
Render/draw.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/draw.cpp.o
.PHONY : Render/draw.cpp.o

Render/draw.i: Render/draw.cpp.i
.PHONY : Render/draw.i

# target to preprocess a source file
Render/draw.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/draw.cpp.i
.PHONY : Render/draw.cpp.i

Render/draw.s: Render/draw.cpp.s
.PHONY : Render/draw.s

# target to generate assembly for a file
Render/draw.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/draw.cpp.s
.PHONY : Render/draw.cpp.s

Render/event.o: Render/event.cpp.o
.PHONY : Render/event.o

# target to build an object file
Render/event.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/event.cpp.o
.PHONY : Render/event.cpp.o

Render/event.i: Render/event.cpp.i
.PHONY : Render/event.i

# target to preprocess a source file
Render/event.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/event.cpp.i
.PHONY : Render/event.cpp.i

Render/event.s: Render/event.cpp.s
.PHONY : Render/event.s

# target to generate assembly for a file
Render/event.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/event.cpp.s
.PHONY : Render/event.cpp.s

Render/render.o: Render/render.cpp.o
.PHONY : Render/render.o

# target to build an object file
Render/render.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/render.cpp.o
.PHONY : Render/render.cpp.o

Render/render.i: Render/render.cpp.i
.PHONY : Render/render.i

# target to preprocess a source file
Render/render.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/render.cpp.i
.PHONY : Render/render.cpp.i

Render/render.s: Render/render.cpp.s
.PHONY : Render/render.s

# target to generate assembly for a file
Render/render.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/render.cpp.s
.PHONY : Render/render.cpp.s

Render/setup.o: Render/setup.cpp.o
.PHONY : Render/setup.o

# target to build an object file
Render/setup.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/setup.cpp.o
.PHONY : Render/setup.cpp.o

Render/setup.i: Render/setup.cpp.i
.PHONY : Render/setup.i

# target to preprocess a source file
Render/setup.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/setup.cpp.i
.PHONY : Render/setup.cpp.i

Render/setup.s: Render/setup.cpp.s
.PHONY : Render/setup.s

# target to generate assembly for a file
Render/setup.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/Render/setup.cpp.s
.PHONY : Render/setup.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/Fluid.dir/build.make src/CMakeFiles/Fluid.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Fluid"
	@echo "... ControlPanel/control_panel.o"
	@echo "... ControlPanel/control_panel.i"
	@echo "... ControlPanel/control_panel.s"
	@echo "... ControlPanel/gui.o"
	@echo "... ControlPanel/gui.i"
	@echo "... ControlPanel/gui.s"
	@echo "... Fluid/fluid.o"
	@echo "... Fluid/fluid.i"
	@echo "... Fluid/fluid.s"
	@echo "... Fluid/logic.o"
	@echo "... Fluid/logic.i"
	@echo "... Fluid/logic.s"
	@echo "... Fluid/util.o"
	@echo "... Fluid/util.i"
	@echo "... Fluid/util.s"
	@echo "... Render/draw.o"
	@echo "... Render/draw.i"
	@echo "... Render/draw.s"
	@echo "... Render/event.o"
	@echo "... Render/event.i"
	@echo "... Render/event.s"
	@echo "... Render/render.o"
	@echo "... Render/render.i"
	@echo "... Render/render.s"
	@echo "... Render/setup.o"
	@echo "... Render/setup.i"
	@echo "... Render/setup.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/runner/work/FluidSimulation/FluidSimulation/build_site && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

